version: "3.9"

services:
  matomo:
    image: matomo
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - .env
